<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Promise TEST</title>
    <style>
        body {
            padding: 16px 32px;
        }

        pre {
            padding: 16px;
            line-height: 2;
            background-color: #f5f5f5;
        }
    </style>
</head>

<body>
    <H3></H3>
    <pre>
    Promise/A+ 规范
    * 1. new Promise时，需要传递一个 executor 执行器，执行器立刻执行
    * 2. executor 接受两个参数，分别是 resolve 和 reject
    * 3. promise 只能从 pending 到 rejected, 或者从 pending 到 fulfilled
    * 4. promise 的状态一旦确认，就不会再改变
    * 5. promise 都有 then 方法，then 接收两个参数，分别是 promise 成功的回调 onFulfilled, 和 promise 失败的回onRejected
    * 6. 如果调用 then 时，promise已经成功，则执行 onFulfilled，并将promise的值作为参数传递进去。
        * 如果promise已经失败，那么执行 onRejected, 并将 promise 失败的原因作为参数传递进去。
        * 如果promise的状态是pending，需要将onFulfilled和onRejected函数存放起来，等待状态确定后，再依次将对应的函数执行(发布订阅)
    * 7. then 的参数 onFulfilled 和 onRejected 可以缺省
    * 8. promise 可以then多次，promise 的then 方法返回一个 promise
    * 9. 如果 then 返回的是一个结果，那么就会把这个结果作为参数，传递给下一个then的成功的回调(onFulfilled)
    * 10. 如果 then 中抛出了异常，那么就会把这个异常作为参数，传递给下一个then的失败的回调(onRejected)
    * 11. 如果 then 返回的是一个promise,那么需要等这个promise，那么会等这个promise执行完，promise如果成功，就走下一个then的成功，如果失败，就走下一个then的失败     
    </pre>

    <script>
        /**
        * Promise 实现 遵循promise/A+规范
        * Promise/A+规范译文:
        * https://malcolmyu.github.io/2015/06/12/Promises-A-Plus/#note-4
        */

        // promise 三个状态
        const PENDING = "Pending";
        const FULFILLED = "Fulfilled";
        const REJECTED = "Rejected";

        function Promise(excutor) {
            this.status = PENDING; // 初始状态
            this.value = undefined; // fulfilled状态时 返回的信息
            this.reason = undefined; // rejected状态时 拒绝的原因
            this.onFulfilledCallbacks = []; // 存储fulfilled状态对应的onFulfilled函数
            this.onRejectedCallbacks = []; // 存储rejected状态对应的onRejected函数

            let self = this; // 缓存当前promise实例对象
            function resolve(value) {
                // 只能由pending状态 => fulfilled状态 (避免调用多次resolve reject)
                if (self.status === PENDING) {
                    self.status = FULFILLED;
                    self.value = value;
                    self.onFulfilledCallbacks.forEach(cb => cb(self.value));
                }
            }

            function reject(reason) {
                // 只能由pending状态 => rejected状态 (避免调用多次resolve reject)
                if (self.status === PENDING) {
                    self.status = REJECTED;
                    self.reason = reason;
                    self.onRejectedCallbacks.forEach(cb => cb(self.reason));
                }
            }

            try {
                excutor(resolve, reject);
            } catch (e) {
                reject(e);
            }
        }

        /**
         * resolve中的值几种情况：
         * 1.普通值
         * 2.promise对象
         * 3.thenable对象/函数
         */

        /**
         * 对resolve 进行改造增强 针对resolve中不同值情况 进行处理
         * @param  {promise} promise2 promise1.then方法返回的新的promise对象
         * @param  {[type]} x         promise1中onFulfilled的返回值
         * @param  {[type]} resolve   promise2的resolve方法
         * @param  {[type]} reject    promise2的reject方法
         */
        function resolvePromise(promise2, x, resolve, reject) {
            if (promise2 === x) {  // 如果从onFulfilled中返回的x 就是promise2 就会导致循环引用报错
                return reject(new TypeError('循环引用'));
            }

            // 判断 x 是否是 promise 对象
            if (x != null && (typeof x === "object" || typeof x === "function")) {
                let called = false; // 避免多次调用
                try {
                    let then = x.then;
                    if (typeof then === 'function') {
                        then.call(x, y => {
                            if (called) return;
                            called = true;
                            resolvePromise(promise2, y, resolve, reject);
                        }, reason => {
                            if (called) return;
                            called = true;
                            reject(reason);
                        })
                    } else { // 说明是一个普通对象/函数
                        resolve(x);
                    }
                } catch (e) {
                    if (called) return;
                    called = true;
                    reject(e);
                }
            } else {
                resolve(x);
            }
        }

        /**
         * [注册fulfilled状态/rejected状态对应的回调函数]
         * @param  {function} onFulfilled fulfilled状态时 执行的函数
         * @param  {function} onRejected  rejected状态时 执行的函数
         * @return {function} newPromsie  返回一个新的promise对象
         */
        Promise.prototype.then = function (onFulfilled, onRejected) {
            let self = this;
            let promise2;
            // 处理参数默认值 保证参数后续能够继续执行
            onFulfilled = typeof onFulfilled === "function" ? onFulfilled : value => { return value };
            onRejected = typeof onRejected === "function" ? onRejected : reason => { throw reason };

            // then里面的FULFILLED/REJECTED状态时 为什么要加setTimeout ?
            // 原因:
            // 其一 2.2.4规范 要确保 onFulfilled 和 onRejected 方法异步执行(且应该在 then 方法被调用的那一轮事件循环之后的新执行栈中执行) 所以要在resolve里加上setTimeout
            // 其二 2.2.6规范 对于一个promise，它的then方法可以调用多次.（当在其他程序中多次调用同一个promise的then时 由于之前状态已经为FULFILLED/REJECTED状态，则会走的下面逻辑),所以要确保为FULFILLED/REJECTED状态后 也要异步执行onFulfilled/onRejected

            // 其二 2.2.6规范 也是resolve函数里加setTimeout的原因
            // 总之都是 让then方法异步执行 也就是确保onFulfilled/onRejected异步执行

            // 如下面这种情景 多次调用p1.then
            // p1.then((value) => { // 此时p1.status 由pending状态 => fulfilled状态
            //     console.log(value); // resolve
            //     // console.log(p1.status); // fulfilled
            //     p1.then(value => { // 再次p1.then 这时已经为fulfilled状态 走的是fulfilled状态判断里的逻辑 所以我们也要确保判断里面onFuilled异步执行
            //         console.log(value); // 'resolve'
            //     });
            //     console.log('当前执行栈中同步代码');
            // })
            // console.log('全局执行栈中同步代码');
            //

            if (self.status === FULFILLED) { // 成功态
                promise2 = new Promise((resolve, reject) => {
                    setTimeout(() => {
                        try {
                            let x = onFulfilled(self.value);
                            resolvePromise(promise2, x, resolve, reject); // 新的promise resolve 上一个onFulfilled的返回值
                        } catch (e) {
                            reject(e); // 捕获前面onFulfilled中抛出的异常 then(onFulfilled, onRejected);
                        }
                    });
                })
                return promise2
            }

            if (self.status === REJECTED) { // 失败态
                promise2 = new Promise((resolve, reject) => {
                    setTimeout(() => {
                        try {
                            let x = onRejected(self.reason);
                            resolvePromise(promise2, x, resolve, reject);
                        } catch (e) {
                            reject(e);
                        }
                    });
                });
                return promise2
            }

            if (self.status === PENDING) {
                // 当异步调用resolve/rejected时 将onFulfilled/onRejected收集暂存到集合中
                // 为什么加setTimeout?
                // 2.2.4规范 onFulfilled 和 onRejected 只允许在 execution context 栈仅包含平台代码时运行.
                // 注1 这里的平台代码指的是引擎、环境以及 promise 的实施代码。实践中要确保 onFulfilled 和 onRejected 方法异步执行，且应该在 then 方法被调用的那一轮事件循环之后的新执行栈中执行。

                promise2 = new Promise((resolve, reject) => {
                    self.onFulfilledCallbacks.push((value) => {
                        setTimeout(() => {
                            try {
                                let x = onFulfilled(value);
                                resolvePromise(promise2, x, resolve, reject);
                            } catch (e) {
                                reject(e);
                            }
                        })
                    });
                    self.onRejectedCallbacks.push((reason) => {
                        setTimeout(() => {
                            try {
                                let x = onRejected(reason);
                                resolvePromise(promise2, x, resolve, reject);
                            } catch (e) {
                                reject(e);
                            }
                        })
                    })
                });
                return promise2
            }
        };

        Promise.resolve = function (value) {
            if (value instanceof Promise) {
                return value;
            }
            return new Promise((resolve, reject) => {
                if (value && value.then && typeof value.then === 'function') {
                    setTimeout(() => {
                        value.then(resolve, reject);
                    });
                } else {
                    resolve(value);
                }
            });

        };


        Promise.reject = function (reason) {
            return new Promise((resolve, reject) => reject(reason));
        };


        Promise.prototype.catch = function (onRejected) {
            return this.then(null, onRejected);
        };


        Promise.prototype.finally = function (callback) {
            return this.then(
                value => {
                    return Promise.resolve(callback()).then(() => {
                        return value;
                    });
                },
                err => {
                    return Promise.resolve(callback()).then(() => {
                        throw err;
                    });
                },
            );
        };

        /**
         * Promise.all Promise进行并行处理
         * 参数: promise对象组成的数组作为参数
         * 返回值: 返回一个Promise实例
         * 当这个数组里的所有promise对象全部变为resolve状态的时候，才会resolve。
         */
        Promise.all = function (promises) {
            return new Promise((resolve, reject) => {
                let count = 0;
                let result = [];
                if (promises.length === 0) {
                    resolve(result);
                } else {
                    for (let i = 0; i < promises.length; i++) {
                        // promises[i] 可能是普通值
                        Promise.resolve(promises[i]).then((data) => {
                            result[i] = data;
                            if (++count === promises.length) {
                                resolve(result);
                            }
                        }, reject);
                    }
                }
            });
        }

        /**
       * Promise.race
       * 参数: 接收 promise对象组成的数组作为参数
       * 返回值: 返回一个Promise实例
       * 只要有一个promise对象进入 FulFilled 或者 Rejected 状态的话，就会继续进行后面的处理(取决于哪一个更快)
       */
        Promise.race = function (promises) {
            if (promises.length === 0) {
                return;
            }
            return new Promise((resolve, reject) => {
                promises.forEach((promise, index) => {
                    Promise.resolve(promise).then(resolve, reject);
                });
            });
        }


        console.log('======== test promise.then ========')
        var promise = new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve('====promise====')
            }, 500);
        }).then((res) => {
            console.log(res)
        })


        console.log('======== test Promise.resolve ========')

        var p = Promise.resolve(20);
        p.then((data) => {
            console.log(data);
        });


        var p2 = Promise.resolve({
            then: function (resolve, reject) {
                resolve(30);
            }
        });

        p2.then((data) => {
            console.log(data)
        });

        var p3 = Promise.resolve(new Promise((resolve, reject) => {
            resolve(400)
        }));
        p3.then((data) => {
            console.log(data)
        });


        console.log('======== test Promise.all ========')

        var promise1 = new Promise((resolve, reject) => {
            resolve(3);
        })
        var promise2 = 42;
        var promise3 = new Promise(function (resolve, reject) {
            setTimeout(resolve, 100, 'foo');
        });

        Promise.all([promise1, promise2, promise3]).then(function (values) {
            console.log(values); //[3, 42, 'foo']
        }, (err) => {
            console.log(err)
        });

        var p = Promise.all([]); // will be immediately resolved
        var p2 = Promise.all([1337, "hi"]); // non-promise values will be ignored, but the evaluation will be done asynchronously
        console.log(p);
        console.log(p2)
        setTimeout(function () {
            console.log('the stack is now empty');
            console.log(p2);
        });

        console.log('======== test Promise.race ========')
        Promise.race([
            new Promise((resolve, reject) => { setTimeout(() => { resolve(100) }, 1000) }),
            undefined,
            new Promise((resolve, reject) => { setTimeout(() => { reject(100) }, 100) })
        ]).then((data) => {
            console.log('success ', data);
        }, (err) => {
            console.log('err ', err);
        });

        Promise.race([
            new Promise((resolve, reject) => { setTimeout(() => { resolve(100) }, 1000) }),
            new Promise((resolve, reject) => { setTimeout(() => { resolve(200) }, 200) }),
            new Promise((resolve, reject) => { setTimeout(() => { reject(100) }, 1000) })
        ]).then((data) => {
            console.log(data);
        }, (err) => {
            console.log(err);
        });
    </script>
</body>

</html>